### PR TITLE
Just a few Kotlin related ideas

### PR DESCRIPTION
**Pull request by wmentzel**

### CODE REVIEW

**Comment by Drako** [comment]
Okay, here are my thoughts on this one:

What I liked the most was the `coerceIn`. I really didn't know about it and it makes the whole `clamp` function obsolete. Nice.

I disliked getting rid of the constants as that serves no purpose what so ever. I would actually hand in the constants to `coerceIn` instead of the two magic numbers. The two constants are pretty much derived from the specification and I see no harm in having them.

Now the other things (`first`, `IntRange.random()`, raw strings) or for one a matter of taste and on the other hand they are just equivalent. There is no real benefit of choosing either of these over what is already there. Meaning in new code, yes, one code argue to write it like that, maybe for consistency or whatever. But if I saw existing code written in either way I would not go out of my way and suggest to change it to the other.

Also using `-quality` instead of `-MAX_QUALITY`... I just find the change unnecessary.

Last but not least I will not accept this PR, because you created it based on "my solution" and want to merge it into "my solution", making "my solution" somewhat "our solution".

**Comment by wmentzel** [comment]
> What I liked the most was the `coerceIn`. I really didn't know about it and it makes the whole clamp function obsolete. Nice.
Great!

> I disliked getting rid of the constants as that serves no purpose what so ever. I would actually hand in the constants to `coerceIn` instead of the two magic numbers. The two constants are pretty much derived from the specification and I see no harm in having them.

Yes, one could keep the constants, but then I would use constants for this as well:

    if (sellIn <= 0) 2 else 1

It just seems arbitrary to use constants for some values and for some not.

> Now the other things (first, IntRange.random(), raw strings) or for one a matter of taste and on the other hand they are just equivalent. There is no real benefit of choosing either of these over what is already there. Meaning in new code, yes, one code argue to write it like that, maybe for consistency or whatever. But if I saw existing code written in either way I would not go out of my way and suggest to change it to the other.

Ok, we agree to disagree.

> Also using -quality instead of -MAX_QUALITY... I just find the change unnecessary.

When you start to transform the code from what it was the setting to 0 was actually achieved by `-item.quality`, so why change that?

> Last but not least I will not accept this PR, because you created it based on "my solution" and want to merge it into "my solution", making "my solution" somewhat "our solution".

Yep, you are right, it would make no sense to merge it, I just wanted to have a place for a discussion. I have to say I totally enjoyed reading your solution because it is so much different from what I came up with.

---

I would really like your opinion on https://github.com/wmentzel/KotlinGildedRose/tree/willis-solution too. You will see that I interpreted some things from the task differently. For me, for example, "Aged Brie" was not a representative of a group. It is just an individual item with its own set of rules. The task mentions "Aged Brie" explicitely on so does the code. For backstage passes it is a different story. Here a class of items is described in the task, but in the code a specific representative item "Backstage passes to a TAFKAL80ETC concert" is mentioned.

**Comment by Drako** [comment]
> Yes, one could keep the constants, but then I would use constants for this as well:
> 
> ```
> if (sellIn <= 0) 2 else 1
> ```
> 
> It just seems arbitrary to use constants for some values and for some not.

You are completely right with that point. Actually that was one of my thoughts when writing my previous response, that one could argue to do the same for these special cases. Tbh I was just being lazy at that point and though of it as not being "a big deal". So yes, for consistency these should also be named constants.

And yes, that might seem arbitrary, but to me there was not much value in giving a bunch of values from -4 up to +3 names,
when they are in a sufficiently named function and only occur once.

> When you start to transform the code from what it was the setting to 0 was actually achieved by `-item.quality`, so why change that?

That was indeed completely arbitrary. I just don't feel like changing it anymore, as, as I said, I don't really feel either being objectively superior.


> > Last but not least I will not accept this PR, because you created it based on "my solution" and want to merge it into "my solution", making "my solution" somewhat "our solution".
> 
> Yep, you are right, it would make no sense to merge it, I just wanted to have a place for a discussion. I have to say I totally enjoyed reading your solution because it is so much different from what I came up with.

I took it as such and again: your points aren't wrong in anyway.
I just don't think that all of them are objectively useful improvements.
And as such I like to stick to what I like subjectively ;-)

> I would really like your opinion on https://github.com/wmentzel/KotlinGildedRose/tree/willis-solution too. You will see that I interpreted some things from the task differently. For me, for example, "Aged Brie" was not a representative of a group. It is just an individual item with its own set of rules. The task mentions "Aged Brie" explicitely on so does the code. For backstage passes it is a different story. Here a class of items is described in the task, but in the code a specific representative item "Backstage passes to a TAFKAL80ETC concert" is mentioned.

I already had a short look on it, but I'd suggest, we discuss that in a call a bit. Makes the whole forth and back smoother.

**Comment by wmentzel** [comment]
> I already had a short look on it, but I'd suggest, we discuss that in a call a bit. Makes the whole forth and back smoother.

Would like that. Let me know when you are available.

**Pull request closed without merging**
